name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Google Chrome
        if: runner.os == 'Windows'
        run: |
          choco install googlechrome --yes --ignore-checksums
      - name: Install dependencies
        run: npm install
      - name: Run Selenium tests
        run: npm test
